### PR TITLE
Update scope.yaml to reflect additional categories.

### PR DESCRIPTION
**Pull request by rofrankel**
Also, recategorize some placeholder AEPs.

### CODE REVIEW

**Review by toumorokoshi — APPROVED** [review]

**Comment by toumorokoshi** [comment]
fyi: lint is failing.

**Comment by mkistler** [comment]
Can you also fix the category of aep/general/0132/aep.yaml to "standard-operations" ?

**Comment by rofrankel** [comment]
> Can you also fix the category of aep/general/0132/aep.yaml to "standard-operations" ?

I made it standard-methods instead, since that already exists.  I also got rid of "operations" entirely, since `Get` moved to standard methods and the other two seem like design patterns.  And operations seems like too broad a category.

Does that work for you @mkistler?

**Review by mkistler — APPROVED** [review]
Looks good! 👍

**Pull request merged**
